name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Format with Prettier
        run: pnpm prettier --check .
      - name: Lint with ESLint
        run: pnpm eslint .
      - name: Build with Vite
        run: pnpm build
